### ISSUE TITLE
tokenizer.model?

### ISSUE THREAD

**Issue by loadingyy** [michaelnny/InstructLLaMA#8]
Thank you for your open-source code first.
In  InstructLLaMA/scripts/convert_meta_checkpoint.py  126 line. What is the tokenizer.model? Is that the tokenizer file in llama2, or the tokenizer.py in InstructLLaMA/models, or something?

**Comment by michaelnny** [comment]
Hi, the `tokenizer.model` is the checkpoint for the tokenizer used by the LLaMA models.
